---
namespace: fmjstudios
name: package_managers
version: 0.0.1
readme: README.md
authors:
  - Maximilian Gindorfer <info@fmj.dev>
description: Ansible Collection for installation and use of package managers
license_file: "LICENSE"
tags:
  - package
  - package manager
  - composer
  - sdkman
  - node-version-manager
  - ruby-version-manager
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: https://fmj.dev
issues: http://example.com/issue/tracker
build_ignore:
  - .gitignore
  - LICENSE
  - Makefile
  - AUTHORS
  - .vscode
  - .github