---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - composer_install
        - composer_configure
        - composer_run
  tags:
    - composer_install
    - composer_configure
    - composer_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - composer_install
  tags:
    - composer_install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - composer_configure
  tags:
    - composer_configure

- name: Ensure composer service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ __composer_systemd_service }}"
    state: started
    enabled: true

- name: Flush handlers after run.
  ansible.builtin.meta: flush_handlers
